(() => {
  const css = `#orbitAI{position:fixed;right:22px;bottom:22px;z-index:20;font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}#orbitAI button{font:inherit;cursor:pointer}#orbitOpen{background:#32176b;color:#fff;border:0;border-radius:99px;padding:13px 18px;box-shadow:0 12px 28px #2d12605c;font-weight:750}#orbitPanel{display:none;position:absolute;right:0;bottom:58px;width:min(410px,calc(100vw - 30px));background:#fff;border:1px solid #e8e0f5;border-radius:21px;box-shadow:0 22px 60px #240a4a38;overflow:hidden}#orbitPanel.show{display:block}.oaHead{background:linear-gradient(135deg,#32176b,#7850ef);color:#fff;padding:17px}.oaHead b{font-size:17px}.oaHead p{font-size:12px;margin:4px 0 0;opacity:.83}.oaBody{padding:15px}.oaChoices{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:12px}.oaChoices button{border:1px solid #e3daf5;background:#f7f3ff;color:#5425b8;border-radius:99px;padding:7px 9px;font-size:12px}.oaChat{min-height:100px;max-height:260px;overflow:auto;font-size:13px;line-height:1.5;color:#312449;white-space:pre-wrap}.oaMsg{background:#f5f1ff;padding:10px;border-radius:12px;margin:8px 0}.oaForm{display:flex;gap:7px;margin-top:12px}.oaForm input{min-width:0;flex:1;border:1px solid #ded5ef;border-radius:11px;padding:10px;font:inherit}.oaForm button{background:#6d3df2;color:#fff;border:0;border-radius:11px;padding:10px 12px;font-weight:700}.oaNote{margin:10px 1px 0;color:#786d89;font-size:11px}`;
  document.head.insertAdjacentHTML('beforeend', `<style>${css}</style>`);
  document.body.insertAdjacentHTML('beforeend', `<div id="orbitAI"><div id="orbitPanel"><div class="oaHead"><b>AI Job Assistant</b><p>Evidence-first guidance. Nothing is submitted automatically.</p></div><div class="oaBody"><div class="oaChoices"><button data-q="Review the NMI role honestly: strongest fit, gaps and experience barrier.">Review this role</button><button data-q="Draft a concise Australian-style professional summary for this role using verified evidence only.">Tailor CV summary</button><button data-q="Give me three truthful selection-criteria examples and label what I must confirm.">Selection criteria</button></div><div class="oaChat"><div class="oaMsg">Ask about fit, CV wording, selection criteria, salary or experience requirements.</div></div><form class="oaForm"><input aria-label="Ask the AI assistant" placeholder="Ask about this role…"><button>Send</button></form><p class="oaNote">Your chat is sent to the configured AI service. Do not paste personal IDs, passwords or API keys.</p></div></div><button id="orbitOpen">✦ AI Assistant</button></div>`);
  const panel=document.querySelector('#orbitPanel'), open=document.querySelector('#orbitOpen'), chat=document.querySelector('.oaChat'), form=document.querySelector('.oaForm'), input=form.querySelector('input');
  open.onclick=()=>panel.classList.toggle('show');
  const ask=async message=>{ chat.insertAdjacentHTML('beforeend',`<div class="oaMsg"><b>You:</b> ${message.replace(/[<>&]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[c]))}</div><div class="oaMsg" id="oaWaiting">Thinking…</div>`);chat.scrollTop=chat.scrollHeight;try{const r=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,mode:'review'})});const d=await r.json();document.querySelector('#oaWaiting').textContent=d.answer||d.error||'Sorry, please try again.'}catch(e){document.querySelector('#oaWaiting').textContent='The secure AI endpoint is unavailable on this preview. Open the deployed secure site.'}chat.scrollTop=chat.scrollHeight;};
  form.onsubmit=e=>{e.preventDefault();const m=input.value.trim();if(m){input.value='';ask(m)}};document.querySelectorAll('.oaChoices button').forEach(b=>b.onclick=()=>ask(b.dataset.q));
})();
